### ISSUE TITLE
training log file

### ISSUE THREAD

**Issue by xlim1997** [junjiehe96/FastInst#11]
Hi,
Thank you for your hard work on FastInst. Could you please provide me with a copy of your training log file?

Best regards,
[Xiaolin]

**Comment by junjiehe96** [comment]
Thank you for your interest in our work. Two model training logs are here. Hope they are helpful for you.
[log.zip](https://github.com/junjiehe96/FastInst/files/12505738/log.zip)

**Comment by xlim1997** [comment]
Thanks a lot.
