### ISSUE TITLE
关于demo.py运行视频和摄像头帧率低问题

### ISSUE THREAD

**Issue by fpeanut** [junjiehe96/FastInst#14]
我用python demo/demo.py --webcam运行你们的demo程序，帧率始终很低是什么原因

**Comment by junjiehe96** [comment]
@fpeanut ，运行demo.py --webcam帧率低是因为：
(1) 需要可视化mask，这部分速度很慢；
(2) 视频帧需要写入和加载；
(3) detectron2 关联相邻帧以获得更好的可视化效果；
对于纯粹的推理速度，建议使用 tools/analyze_model.py 来评估。

**Comment by fpeanut** [comment]
> @fpeanut ，运行demo.py --webcam帧率低是因为： (1) 需要可视化mask，这部分速度很慢； (2) 视频帧需要写入和加载； (3) detectron2 关联相邻帧以获得更好的可视化效果； 对于纯粹的推理速度，建议使用 tools/analyze_model.py 来评估。

好的谢谢，另外我有一个想法，你们的模型有试过转成onnx，trt模型吗，用trt部署是否可行

**Comment by junjiehe96** [comment]
> > @fpeanut ，运行demo.py --webcam帧率低是因为： (1) 需要可视化mask，这部分速度很慢； (2) 视频帧需要写入和加载； (3) detectron2 关联相邻帧以获得更好的可视化效果； 对于纯粹的推理速度，建议使用 tools/analyze_model.py 来评估。
> 
> 好的谢谢，另外我有一个想法，你们的模型有试过转成onnx，trt模型吗，用trt部署是否可行

听起来应该是可行的，我没有尝试过，你可以自己试试

**Comment by leixiaoning** [comment]
> > > @fpeanut ，运行demo.py --webcam帧率低是因为： (1) 需要可视化mask，这部分速度很慢； (2) 视频帧需要写入和加载； (3) detectron2 关联相邻帧以获得更好的可视化效果； 对于纯粹的推理速度，建议使用 tools/analyze_model.py 来评估。
> > 
> > 
> > 好的谢谢，另外我有一个想法，你们的模型有试过转成onnx，trt模型吗，用trt部署是否可行
> 
> 听起来应该是可行的，我没有尝试过，你可以自己试试

当前代码的 deform_conv2d 是不是不支持 要自己写映射规则的符号函数哇？
