### ISSUE TITLE
关于模型的输出结果分析

### ISSUE THREAD

**Issue by fpeanut** [junjiehe96/FastInst#15]
你好，我在打印一张图像的检测结果时，发现输出的结果是由premask、bbox、socres、classes;其中bbox为什么输出的100x4尺寸的tensor值都是0，还有已经有了阈值限制，为什么输出的类别数都是100个

**Comment by junjiehe96** [comment]
1. 可以取消 [这行](https://github.com/junjiehe96/FastInst/blob/4996a613ef86305a58e990fa414f5957a5639cbe/fastinst/fastinst.py#L382) 注释获取box坐标；
2. 你可以参考#2
