### ISSUE TITLE
关于模型的输入

### ISSUE THREAD

**Issue by fpeanut** [junjiehe96/FastInst#16]
你好，请问模型的输入尺寸是动态尺寸吗，还是静态定好的尺寸。尺寸的格式是怎样的

**Comment by junjiehe96** [comment]
默认是动态的，以fastinst_R50_ppm-fpn_x3_640.yaml为例，先短边Resize到640，等比例缩放，如果此时长边超过了853，则按照最长边853重新缩放；然后将图像高宽补零至32的倍数；

当然如果给定图片尺寸是固定的话也可以设置成静态输入；

**Comment by fpeanut** [comment]
> 默认是动态的，以fastinst_R50_ppm-fpn_x3_640.yaml为例，先短边Resize到640，等比例缩放，如果此时长边超过了853，则按照最长边853重新缩放；然后将图像高宽补零至32的倍数；
> 
> 当然如果给定图片尺寸是固定的话也可以设置成静态输入；

我理解的是，是不是最终的输入是不是一个1x3x640x853的数据格式的数据

**Comment by fpeanut** [comment]
![image](https://github.com/junjiehe96/FastInst/assets/58199989/a3fedf4b-5fed-40dd-a8ba-4daaffeb98d6)
我在你推理的代码处，看到的模型输入是一个字典，那他输入的数据格式是什么样的，我这边需要知道数据的格式，才能转到onnx

**Comment by junjiehe96** [comment]
1. 字典中 'image‘ 是网络输入，大小为1x3xHxW的张量，其中H、W是32的整数倍（建议短边为640）；
2. ‘height’和'width'用于网络输出后处理，[line](https://github.com/junjiehe96/FastInst/blob/4996a613ef86305a58e990fa414f5957a5639cbe/fastinst/fastinst.py#L244)

转onnx应该只需要 'image' 作为输入

**Comment by fpeanut** [comment]
> 1. 字典中 'image‘ 是网络输入，大小为1x3xHxW的张量，其中H、W是32的整数倍（建议短边为640）；
> 2. ‘height’和'width'用于网络输出后处理，[line](https://github.com/junjiehe96/FastInst/blob/4996a613ef86305a58e990fa414f5957a5639cbe/fastinst/fastinst.py#L244)
> 
> 转onnx应该只需要 'image' 作为输入

好的，感谢感谢

**Comment by Williamwsk** [comment]
> > 1. 字典中 'image‘ 是网络输入，大小为1x3xHxW的张量，其中H、W是32的整数倍（建议短边为640）；
> > 2. ‘height’和'width'用于网络输出后处理，[line](https://github.com/junjiehe96/FastInst/blob/4996a613ef86305a58e990fa414f5957a5639cbe/fastinst/fastinst.py#L244)
> > 
> > 转onnx应该只需要 'image' 作为输入
> 
> 好的，感谢感谢

您好，可以提供下您实现的 fastinst 转 onnx的相关代码不？万分感谢
