### ISSUE TITLE
How to test models with "coco_2017_test-dev"

### ISSUE THREAD

**Issue by xlim1997** [junjiehe96/FastInst#19]
I download the "image_info_test-dev2017.json" in COCO. And use the "coco_2017_test-dev" as the TEST DATASET. When I run the train_net.py to evaluate the model, I can't get the accuracy and the result shows "Annotations are not available for evaluation." 

If you can help me to solve the problem,I really appreciate it.

**Comment by junjiehe96** [comment]
1. set DATASET.TEST as "coco_2017_test-dev" and run train_net.py --eval-only to get results.
2. upload results to [evaluation server](https://codalab.lisn.upsaclay.fr/competitions/7383#learn_the_details). For details you can refer to [this](https://cocodataset.org/#upload).

**Comment by xlim1997** [comment]
thanks a lot

**Comment by xlim1997** [comment]
I'm sorry to bother you again.
I got the coco_instances_results.json from the model, which is 1.2GB. I can only compress it to 380MB with zip. 
And when I submitted it to https://codalab.lisn.upsaclay.fr/competitions/7383. Submissions are constantly failing with error elapsed time.

If you can help me to solve the problem, I will appreciate it.

error detail:
elapsedTime: 174.19653415679932
exitCode: 137
ingestionExitCode: 0

**Comment by junjiehe96** [comment]
@xlim1996 Hi, the size is right. I tried some times in such case and it finally processed successfully.

**Comment by xlim1997** [comment]
Thanks a lot. I will try to figure it out.
