### ISSUE TITLE
about datasets/prepare_coco_semantic_annos_from_panoptic_annos.py

### ISSUE THREAD

**Issue by fuzhao123232** [junjiehe96/FastInst#20]
thanks for your job. I have a question: why COCO Instance Segmentation need panoptic_annos in the eval stage?

**Comment by fuzhao123232** [comment]
if i don't have panoptic annos ,can i skip this eval step? Now I am training my custom datasets

**Comment by junjiehe96** [comment]
hi, thanks for your interest in our work. Training COCO Instance Segmentation (i.e., cfg.DATASETS.TRAIN=("coco_2017_train",) only requires instance annotations. If you want to training your own datasets, you can refer to [this](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html#register-a-coco-format-dataset) to register your datasets in detectron2 format, and then use our fastinst dataset mapper to process them.

**Comment by fuzhao123232** [comment]
![image](https://github.com/junjiehe96/FastInst/assets/115547529/2af9928d-f4a3-481d-88b0-80c9c0d272de)
大哥，因为你们这里要求了要运行这个脚本生成语义标签的，但是我没有语义标签，所以运行这个就报错了。我的数据集已经注册了，并且可以train和demo推理；
![image](https://github.com/junjiehe96/FastInst/assets/115547529/92536eeb-dbfa-435e-8f19-3928f920c537)
但是zh这是因为我注释了所有train里面eval的步骤
![image](https://github.com/junjiehe96/FastInst/assets/115547529/979666f6-d773-42b6-acd1-7346fc6926e7)
如果不注释的话，就会报这个错：
![image](https://github.com/junjiehe96/FastInst/assets/115547529/fdbc3c92-09e9-4085-b095-ca136d41b713)
然后我的segm是这样的
![image](https://github.com/junjiehe96/FastInst/assets/115547529/e3d9ed89-03e3-442d-8e0b-81ec556c3847)

**Comment by fuzhao123232** [comment]
我的标签仔细检查了没有问题，并且如果有问题的话，我的infer应该会很异常，但我的推理也是正常的

**Comment by fuzhao123232** [comment]
![Uploading image.png…]()
因为我的标签里面的iscrowd是=0的，所以标签都是polygon，train和demo都正常，但eval好像要求我的格式是rle，就很奇怪

**Comment by junjiehe96** [comment]
1. python datasets/prepare_coco_semantic_annos_from_panoptic_annos.py 用来全景分割，否则不是必须的；
2. 如您所说，可以尝试将polygon转成rle；
