### ISSUE TITLE
关于添加无目标背景图进行训练

### ISSUE THREAD

**Issue by fuzhao123232** [junjiehe96/FastInst#21]
作者您好，我们想把背景图也加入网络进行训练，但发现根本不使用背景图，参考了一些方案依旧无效，https://github.com/facebookresearch/detectron2/issues/819 ，请问是因为网络设计本身不允许加入背景图还是在dataloader哪里已经过滤？

**Comment by junjiehe96** [comment]
你好，可以试试将 DATALOADER.FILTER_EMPTY_ANNOTATIONS 设置为False，它会过滤一些没有实例标注的图片

**Comment by junjiehe96** [comment]
你好，模型和dataset_mapper本身是支持无目标背景图作为输入的
