### ISSUE TITLE
关于小目标的问题

### ISSUE THREAD

**Issue by fuzhao123232** [junjiehe96/FastInst#22]
请问作者，因为在论文里面看到有说，该分割器对小目标不太友好，是否是因为是把pixde decoder 的最后一层1/8size的feature map送入transformer deocde？如果我再把1/8size的再upsample +conv 变成1/4再送入transformer decoder这样是否能够提高分割的精度并且对小目标有一个更好的效果？即使牺牲一点推理速度也是没有关系

**Comment by junjiehe96** [comment]
你好，是的，增大输入分辨率或者添加1/4 feature map都可以直接提高小目标的效果
