### ISSUE TITLE
Model does not output bounding boxes

### ISSUE THREAD

**Issue by michalt38** [junjiehe96/FastInst#28]
I am visualizing results of FastInst model using demo.py. Mask segmentation of objects are correct but all bounding boxes are in top-left corner of an image. Is this behaviour expected?

**Comment by junjiehe96** [comment]
Yes,  by default all boxes are set to zeros for fast inference. See [this line](https://github.com/junjiehe96/FastInst/blob/4996a613ef86305a58e990fa414f5957a5639cbe/fastinst/fastinst.py#L380C9-L380C69) for detail.
