### ISSUE TITLE
bbox任务的AP值为空值

### ISSUE THREAD

**Issue by 923468074** [junjiehe96/FastInst#49]
您好，我在使用该模型运行自己的数据集时，检测bbox任务的AP值为空值，模型也无法对图像进行分类，
![屏幕截图 2024-10-28 141055](https://github.com/user-attachments/assets/65c14bf5-9926-45ff-9bde-e8a57e25905f)
但是segm分割任务的AP值却有数值，您能告诉我我在训练时可能犯的错误是什么吗？

**Comment by yielong** [comment]
hi，您有发现是什么原因导致的吗，我也遇到了这种情况

**Comment by yielong** [comment]
https://github.com/junjiehe96/FastInst/blob/4996a613ef86305a58e990fa414f5957a5639cbe/fastinst/fastinst.py#L381

**Comment by 923468074** [comment]
谢谢您，我已经解决了
