### ISSUE TITLE
GPU computational resources quantity

### ISSUE THREAD

**Issue by danhntd** [junjiehe96/FastInst#6]
Dear Authors,
Thank you for your very interesting work and source code.

Could you please confirm the number of GPUs used in the training process? Whether it is 1x V100 or 4x V100?
In the paper, it is indicated that 1x A100 GPU is used to evaluate and infer. But in the source code, 4x GPU is pre-set up in the script.

Many thanks in advance.

**Comment by junjiehe96** [comment]
Thank you for your interest in our work. We used 4x V100 GPUs for model training and 1x V100 for model speed evaluation.
